services:
  app:
    build: .
    container_name: flatornot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LISTEN_ADDR=:3000
      - DB_HOST=postgres
      - DB_USER=testuser
      - DB_PASS=testpassword
      - DB_NAME=testdb
      - DB_PORT=5432
    ports:
      - 3000:3000

  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
